CREATE TABLE IF NOT EXISTS `COMPANIES` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(45) NOT NULL,
    `EMAIL` VARCHAR(45) NOT NULL,
    `PASSWORD` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `CUSTOMERS` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`FIRST_NAME` VARCHAR(45) NOT NULL,
	`LAST_NAME` VARCHAR(45) NOT NULL,
	`EMAIL` VARCHAR(45) NOT NULL,
	`PASSWORD` VARCHAR(45) NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `CATEGORIES` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`ID`),
    UNIQUE INDEX `NAME_UNIQUE` (`NAME` ASC) VISIBLE
);

CREATE TABLE IF NOT EXISTS `COUPONS` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`COMPANY_ID` int NOT NULL,
	`CATEGORY_ID` int NOT NULL,
	`TITLE` VARCHAR(45) NOT NULL,
	`DESCRIPTION` VARCHAR(128) NOT NULL,
	`START_DATE` DATE NOT NULL,
	`END_DATE` DATE NOT NULL,
	`AMOUNT` INT NOT NULL,
	`PRICE` DOUBLE NOT NULL,
	`IMAGE` VARCHAR(128) NOT NULL,
	PRIMARY KEY (`ID`),
    FOREIGN KEY (COMPANY_ID) REFERENCES COMPANIES(ID),
	FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(ID)
);


CREATE TABLE IF NOT EXISTS `COSTUMERS_VS_COUPONS` (
           `CUSTOMER_ID` INT NOT NULL,
           `COUPON_ID` INT NOT NULL,
            PRIMARY KEY (CUSTOMER_ID, COUPON_ID),
            FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID),
            FOREIGN KEY (COUPON_ID) REFERENCES COUPONS(ID)
);